Move trap incase of cd failure - thanks adam brown

diff --git a/bin/site-upgrade b/bin/site-upgrade
--- a/bin/site-upgrade
+++ b/bin/site-upgrade
@@ -85,9 +85,6 @@ if [ "$1" == "all" ]; then
   exit 0
 fi
 
-## enforce cleanup
-trap finish EXIT
-
 CURRENT_SITE="$(basename "$PWD")"
 cd ~/sites/"$CURRENT_SITE/"
 
@@ -100,6 +97,9 @@ header "Upgrading: ${GREEN}$CURRENT_SITE${NC}"
 
 ## pause for user
 sleep 1.5
+
+## enforce cleanup
+trap finish EXIT
 
 sub_task_divider "Getting GitHub ready..."
 
